version: "3"
networks:
  coin-challenge-network:
    driver: bridge

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - coin-challenge-network
    environment:
      POSTGRES_DB: image_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - coin-challenge-network
    environment:
      REACT_APP_API_URL: "http://nginx/coin-api"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - coin-challenge-network

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: image_db
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - coin-challenge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
